name: vondel

services:
  backend:
    container_name: vondel-backend
    build:
      context: ./vondel-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./vondel-backend/environments/.env.docker
    environment:
      DOCKER: "true"
    user: "${MY_UID}:${MY_GID}"
    volumes:
      - ./vondel-backend:/app:cached    # mount host code for hot-reload
      - /app/node_modules               # keep container node_modules intact
    depends_on:
      - db

  frontend:
    container_name: vondel-frontend
    build:
      context: ./vondel-frontend
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./vondel-frontend:/app
      - backend_node_modules:/app/node_modules
    tty: true
    stdin_open: true
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: vondel-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: vondel
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vondel-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vondel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
  backend_node_modules: